### ISSUE TITLE
Notes for Sync 1.20.20

### ISSUE THREAD

**Issue by wesbubeck** [wesbubeck/charity-be#29]
- Walk Through PR dev => master
- Which Branch to target? (Should we change Branches remove Dev, Dev becomes Master and add Prod)
- issue #32 
- handle dates better
- readme updates for graphql
- weekly cadence for standup
- how should we handle PRs from dev => master
- kanban board
- What is next?

**Comment by RJPerry23d** [comment]
Did you send out a new video chat link for tonight?
