### ISSUE TITLE
Update readme file with new info

### ISSUE THREAD

**Issue by RJPerry23d** [wesbubeck/charity-be#35]
Go over Wes' input on the readme file and update incrementally the file

**Comment by wesbubeck** [comment]
@RJPerry23d Below is the email I sent we can walk through it when we sync.

- That app will give volunteers the ability to search local charities and events. Volunteers will be able to favorite charities and view attended request. Charities will be able to manage volunteers data and event data.

- Development: Will need mongodb installed locally <insert link to installing mongo on mongodb website> . Pull down repo, npm install, will need mongo running, in terminal run `npm run start`

- Unit test are in Jest <insert link to jest> mongo test use jest-mongodb which is mongo in memory <https://github.com/shelfio/jest-mongodb> to run test in terminal run `npm run test` to run test in watch mode `npm run test:watch`

- Linting: Uses eslint with modified Airbnb rules to run lint in terminal run `npm run lint` to run lint and auto fix in terminal run `npm run lint:fix`

- Development Branches should be based off master and name convention is <your initials>-issue-<issue number> for example John Doe's branch for issue number 20 would be `jd-issue-20` 

- Pull request: For pull request to merge all unit test need to pass and eslint pass, Github Actions run these on a push. You will need at least 1 reviewer on a PR to sign off for it to merge. If you have more than several commits please squash them before merging in case they need to be reverted. In the comments of your pr please include `closing issues keywords` <https://help.github.com/en/github/managing-your-work-on-github/closing-issues-using-keywords> 

- graphql ( this should probably be its own card ) link to doc for `Apollo Server 2.x` as well as example queries and mutations

**Comment by RJPerry23d** [comment]
@wesbubeck Will be working on this later tonight. today got away from me. Away for awhile and will be back later

**Comment by wesbubeck** [comment]
@RJPerry23d No worries. I just wanted to get those thoughts down. Are you good to chat on Thursday?

**Comment by RJPerry23d** [comment]
Yes I will be able to Chat Thursday.

RJ Perry

(919) 520-4635

**Comment by RJPerry23d** [comment]
Updates all but the following
graphql ( this should probably be its own card ) link to doc for Apollo Server 2.x as well as example queries and mutations Will make that a new issue.
