### ISSUE TITLE
Update graphql info to readme.md file

### ISSUE THREAD

**Issue by RJPerry23d** [wesbubeck/charity-be#45]
graphql ( this should probably be its own card ) link to doc for Apollo Server 2.x as well as example queries and mutations

**Comment by wesbubeck** [comment]
@RJPerry23d I missed a few things in the review can you move them into this card
-  we forgot `npm start` to start the apollo server
- we dont need the run after the npm commands for example `npm run test:watch` should just be `npm test:watcj`
